name: Icon Helper
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run:
          - "python -m pip install --upgrade pip"
          - "pip install -r requirements.txt"
      - name: Run generation test
        run:
          - "mv src/iconhelper.py test"
          - "cd test"
          - "python iconhelper.py --source sample.png --platform MacOS"
          - "python iconhelper.py --source sample.png --platform Windows"
          - "python iconhelper.py --source sample.png --platform Android"
          - "python iconhelper.py --clean"
          - "python iconhelper.py --source sample.png"
